Food = input("Enter your type of food: ")
Plant = input("Enter the type of plant you like: ")
Cook = input("Enter the method for your reciepe: ")
Burn = input("Enter a word to describe burned food: ")
Item = input("Enter the household item: ")
print()
print(Cook, Food, "with", Burn, Plant, "on a bed of", Item)
